"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/header/Header";
import Footer from "@/components/common/footer/Footer";
import { Toaster } from "sonner";
import { useUserStore } from "@/store/userStore";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname();
  const { isAdmin } = useUserStore();

  const isAdminRoute = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {!isAdminRoute && <Header />}

        <main className="min-h-screen flex flex-col justify-center">
          {children}
        </main>

        {!isAdminRoute && <Footer />}

        <Toaster />
      </body>
    </html>
  );
}
